#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ManagerRounds")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertClasificaciones(Clasificaciones instance);
    partial void UpdateClasificaciones(Clasificaciones instance);
    partial void DeleteClasificaciones(Clasificaciones instance);
    partial void InsertEstatusRevision(EstatusRevision instance);
    partial void UpdateEstatusRevision(EstatusRevision instance);
    partial void DeleteEstatusRevision(EstatusRevision instance);
    partial void InsertManagerSecciones(ManagerSecciones instance);
    partial void UpdateManagerSecciones(ManagerSecciones instance);
    partial void DeleteManagerSecciones(ManagerSecciones instance);
    partial void InsertPreguntas(Preguntas instance);
    partial void UpdatePreguntas(Preguntas instance);
    partial void DeletePreguntas(Preguntas instance);
    partial void InsertRespuestasRevision(RespuestasRevision instance);
    partial void UpdateRespuestasRevision(RespuestasRevision instance);
    partial void DeleteRespuestasRevision(RespuestasRevision instance);
    partial void InsertRevisiones(Revisiones instance);
    partial void UpdateRevisiones(Revisiones instance);
    partial void DeleteRevisiones(Revisiones instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    partial void InsertTiposArea(TiposArea instance);
    partial void UpdateTiposArea(TiposArea instance);
    partial void DeleteTiposArea(TiposArea instance);
    partial void InsertTiposCheck(TiposCheck instance);
    partial void UpdateTiposCheck(TiposCheck instance);
    partial void DeleteTiposCheck(TiposCheck instance);
    partial void InsertTiposRespuesta(TiposRespuesta instance);
    partial void UpdateTiposRespuesta(TiposRespuesta instance);
    partial void DeleteTiposRespuesta(TiposRespuesta instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertSecciones(Secciones instance);
    partial void UpdateSecciones(Secciones instance);
    partial void DeleteSecciones(Secciones instance);
    partial void InsertNotificaciones(Notificaciones instance);
    partial void UpdateNotificaciones(Notificaciones instance);
    partial void DeleteNotificaciones(Notificaciones instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Datos.Properties.Settings.Default.ManagerRoundsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clasificaciones> Clasificaciones
		{
			get
			{
				return this.GetTable<Clasificaciones>();
			}
		}
		
		public System.Data.Linq.Table<EstatusRevision> EstatusRevision
		{
			get
			{
				return this.GetTable<EstatusRevision>();
			}
		}
		
		public System.Data.Linq.Table<ManagerSecciones> ManagerSecciones
		{
			get
			{
				return this.GetTable<ManagerSecciones>();
			}
		}
		
		public System.Data.Linq.Table<Preguntas> Preguntas
		{
			get
			{
				return this.GetTable<Preguntas>();
			}
		}
		
		public System.Data.Linq.Table<RespuestasRevision> RespuestasRevision
		{
			get
			{
				return this.GetTable<RespuestasRevision>();
			}
		}
		
		public System.Data.Linq.Table<Revisiones> Revisiones
		{
			get
			{
				return this.GetTable<Revisiones>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
		
		public System.Data.Linq.Table<TiposArea> TiposArea
		{
			get
			{
				return this.GetTable<TiposArea>();
			}
		}
		
		public System.Data.Linq.Table<TiposCheck> TiposCheck
		{
			get
			{
				return this.GetTable<TiposCheck>();
			}
		}
		
		public System.Data.Linq.Table<TiposRespuesta> TiposRespuesta
		{
			get
			{
				return this.GetTable<TiposRespuesta>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Secciones> Secciones
		{
			get
			{
				return this.GetTable<Secciones>();
			}
		}
		
		public System.Data.Linq.Table<Notificaciones> Notificaciones
		{
			get
			{
				return this.GetTable<Notificaciones>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clasificaciones")]
	public partial class Clasificaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Clasificacion;
		
		private EntitySet<Preguntas> _Preguntas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnClasificacionChanging(string value);
    partial void OnClasificacionChanged();
    #endregion
		
		public Clasificaciones()
		{
			this._Preguntas = new EntitySet<Preguntas>(new Action<Preguntas>(this.attach_Preguntas), new Action<Preguntas>(this.detach_Preguntas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clasificacion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Clasificacion
		{
			get
			{
				return this._Clasificacion;
			}
			set
			{
				if ((this._Clasificacion != value))
				{
					this.OnClasificacionChanging(value);
					this.SendPropertyChanging();
					this._Clasificacion = value;
					this.SendPropertyChanged("Clasificacion");
					this.OnClasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clasificaciones_Preguntas", Storage="_Preguntas", ThisKey="id", OtherKey="Clasificacion_id")]
		public EntitySet<Preguntas> Preguntas
		{
			get
			{
				return this._Preguntas;
			}
			set
			{
				this._Preguntas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Preguntas(Preguntas entity)
		{
			this.SendPropertyChanging();
			entity.Clasificaciones = this;
		}
		
		private void detach_Preguntas(Preguntas entity)
		{
			this.SendPropertyChanging();
			entity.Clasificaciones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EstatusRevision")]
	public partial class EstatusRevision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Estatus;
		
		private EntitySet<Revisiones> _Revisiones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnEstatusChanging(string value);
    partial void OnEstatusChanged();
    #endregion
		
		public EstatusRevision()
		{
			this._Revisiones = new EntitySet<Revisiones>(new Action<Revisiones>(this.attach_Revisiones), new Action<Revisiones>(this.detach_Revisiones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstatusRevision_Revisiones", Storage="_Revisiones", ThisKey="id", OtherKey="Estatus_id")]
		public EntitySet<Revisiones> Revisiones
		{
			get
			{
				return this._Revisiones;
			}
			set
			{
				this._Revisiones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Revisiones(Revisiones entity)
		{
			this.SendPropertyChanging();
			entity.EstatusRevision = this;
		}
		
		private void detach_Revisiones(Revisiones entity)
		{
			this.SendPropertyChanging();
			entity.EstatusRevision = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManagerSecciones")]
	public partial class ManagerSecciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Usuario_id;
		
		private string _Seccion;
		
		private int _TipoArea_id;
		
		private int _TipoCheck_id;
		
		private bool _Activo;
		
		private EntitySet<Revisiones> _Revisiones;
		
		private EntityRef<TiposArea> _TiposArea;
		
		private EntityRef<TiposCheck> _TiposCheck;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUsuario_idChanging(int value);
    partial void OnUsuario_idChanged();
    partial void OnSeccionChanging(string value);
    partial void OnSeccionChanged();
    partial void OnTipoArea_idChanging(int value);
    partial void OnTipoArea_idChanged();
    partial void OnTipoCheck_idChanging(int value);
    partial void OnTipoCheck_idChanged();
    partial void OnActivoChanging(bool value);
    partial void OnActivoChanged();
    #endregion
		
		public ManagerSecciones()
		{
			this._Revisiones = new EntitySet<Revisiones>(new Action<Revisiones>(this.attach_Revisiones), new Action<Revisiones>(this.detach_Revisiones));
			this._TiposArea = default(EntityRef<TiposArea>);
			this._TiposCheck = default(EntityRef<TiposCheck>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_id", DbType="Int NOT NULL")]
		public int Usuario_id
		{
			get
			{
				return this._Usuario_id;
			}
			set
			{
				if ((this._Usuario_id != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuario_idChanging(value);
					this.SendPropertyChanging();
					this._Usuario_id = value;
					this.SendPropertyChanged("Usuario_id");
					this.OnUsuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Seccion
		{
			get
			{
				return this._Seccion;
			}
			set
			{
				if ((this._Seccion != value))
				{
					this.OnSeccionChanging(value);
					this.SendPropertyChanging();
					this._Seccion = value;
					this.SendPropertyChanged("Seccion");
					this.OnSeccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoArea_id", DbType="Int NOT NULL")]
		public int TipoArea_id
		{
			get
			{
				return this._TipoArea_id;
			}
			set
			{
				if ((this._TipoArea_id != value))
				{
					if (this._TiposArea.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoArea_idChanging(value);
					this.SendPropertyChanging();
					this._TipoArea_id = value;
					this.SendPropertyChanged("TipoArea_id");
					this.OnTipoArea_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCheck_id", DbType="Int NOT NULL")]
		public int TipoCheck_id
		{
			get
			{
				return this._TipoCheck_id;
			}
			set
			{
				if ((this._TipoCheck_id != value))
				{
					if (this._TiposCheck.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoCheck_idChanging(value);
					this.SendPropertyChanging();
					this._TipoCheck_id = value;
					this.SendPropertyChanged("TipoCheck_id");
					this.OnTipoCheck_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManagerSecciones_Revisiones", Storage="_Revisiones", ThisKey="id", OtherKey="ManagerSeccion_id")]
		public EntitySet<Revisiones> Revisiones
		{
			get
			{
				return this._Revisiones;
			}
			set
			{
				this._Revisiones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposArea_ManagerSecciones", Storage="_TiposArea", ThisKey="TipoArea_id", OtherKey="id", IsForeignKey=true)]
		public TiposArea TiposArea
		{
			get
			{
				return this._TiposArea.Entity;
			}
			set
			{
				TiposArea previousValue = this._TiposArea.Entity;
				if (((previousValue != value) 
							|| (this._TiposArea.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TiposArea.Entity = null;
						previousValue.ManagerSecciones.Remove(this);
					}
					this._TiposArea.Entity = value;
					if ((value != null))
					{
						value.ManagerSecciones.Add(this);
						this._TipoArea_id = value.id;
					}
					else
					{
						this._TipoArea_id = default(int);
					}
					this.SendPropertyChanged("TiposArea");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposCheck_ManagerSecciones", Storage="_TiposCheck", ThisKey="TipoCheck_id", OtherKey="id", IsForeignKey=true)]
		public TiposCheck TiposCheck
		{
			get
			{
				return this._TiposCheck.Entity;
			}
			set
			{
				TiposCheck previousValue = this._TiposCheck.Entity;
				if (((previousValue != value) 
							|| (this._TiposCheck.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TiposCheck.Entity = null;
						previousValue.ManagerSecciones.Remove(this);
					}
					this._TiposCheck.Entity = value;
					if ((value != null))
					{
						value.ManagerSecciones.Add(this);
						this._TipoCheck_id = value.id;
					}
					else
					{
						this._TipoCheck_id = default(int);
					}
					this.SendPropertyChanged("TiposCheck");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_ManagerSecciones", Storage="_Usuarios", ThisKey="Usuario_id", OtherKey="id", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.ManagerSecciones.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.ManagerSecciones.Add(this);
						this._Usuario_id = value.id;
					}
					else
					{
						this._Usuario_id = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Revisiones(Revisiones entity)
		{
			this.SendPropertyChanging();
			entity.ManagerSecciones = this;
		}
		
		private void detach_Revisiones(Revisiones entity)
		{
			this.SendPropertyChanging();
			entity.ManagerSecciones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Preguntas")]
	public partial class Preguntas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Check_id;
		
		private int _Clasificacion_id;
		
		private int _TipoArea_id;
		
		private string _Pregunta;
		
		private bool _Activo;
		
		private EntitySet<RespuestasRevision> _RespuestasRevision;
		
		private EntityRef<Clasificaciones> _Clasificaciones;
		
		private EntityRef<TiposArea> _TiposArea;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCheck_idChanging(string value);
    partial void OnCheck_idChanged();
    partial void OnClasificacion_idChanging(int value);
    partial void OnClasificacion_idChanged();
    partial void OnTipoArea_idChanging(int value);
    partial void OnTipoArea_idChanged();
    partial void OnPreguntaChanging(string value);
    partial void OnPreguntaChanged();
    partial void OnActivoChanging(bool value);
    partial void OnActivoChanged();
    #endregion
		
		public Preguntas()
		{
			this._RespuestasRevision = new EntitySet<RespuestasRevision>(new Action<RespuestasRevision>(this.attach_RespuestasRevision), new Action<RespuestasRevision>(this.detach_RespuestasRevision));
			this._Clasificaciones = default(EntityRef<Clasificaciones>);
			this._TiposArea = default(EntityRef<TiposArea>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_id", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Check_id
		{
			get
			{
				return this._Check_id;
			}
			set
			{
				if ((this._Check_id != value))
				{
					this.OnCheck_idChanging(value);
					this.SendPropertyChanging();
					this._Check_id = value;
					this.SendPropertyChanged("Check_id");
					this.OnCheck_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clasificacion_id", DbType="Int NOT NULL")]
		public int Clasificacion_id
		{
			get
			{
				return this._Clasificacion_id;
			}
			set
			{
				if ((this._Clasificacion_id != value))
				{
					if (this._Clasificaciones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClasificacion_idChanging(value);
					this.SendPropertyChanging();
					this._Clasificacion_id = value;
					this.SendPropertyChanged("Clasificacion_id");
					this.OnClasificacion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoArea_id", DbType="Int NOT NULL")]
		public int TipoArea_id
		{
			get
			{
				return this._TipoArea_id;
			}
			set
			{
				if ((this._TipoArea_id != value))
				{
					if (this._TiposArea.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoArea_idChanging(value);
					this.SendPropertyChanging();
					this._TipoArea_id = value;
					this.SendPropertyChanged("TipoArea_id");
					this.OnTipoArea_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pregunta", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Pregunta
		{
			get
			{
				return this._Pregunta;
			}
			set
			{
				if ((this._Pregunta != value))
				{
					this.OnPreguntaChanging(value);
					this.SendPropertyChanging();
					this._Pregunta = value;
					this.SendPropertyChanged("Pregunta");
					this.OnPreguntaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Preguntas_RespuestasRevision", Storage="_RespuestasRevision", ThisKey="id", OtherKey="Pregunta_id")]
		public EntitySet<RespuestasRevision> RespuestasRevision
		{
			get
			{
				return this._RespuestasRevision;
			}
			set
			{
				this._RespuestasRevision.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clasificaciones_Preguntas", Storage="_Clasificaciones", ThisKey="Clasificacion_id", OtherKey="id", IsForeignKey=true)]
		public Clasificaciones Clasificaciones
		{
			get
			{
				return this._Clasificaciones.Entity;
			}
			set
			{
				Clasificaciones previousValue = this._Clasificaciones.Entity;
				if (((previousValue != value) 
							|| (this._Clasificaciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clasificaciones.Entity = null;
						previousValue.Preguntas.Remove(this);
					}
					this._Clasificaciones.Entity = value;
					if ((value != null))
					{
						value.Preguntas.Add(this);
						this._Clasificacion_id = value.id;
					}
					else
					{
						this._Clasificacion_id = default(int);
					}
					this.SendPropertyChanged("Clasificaciones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposArea_Preguntas", Storage="_TiposArea", ThisKey="TipoArea_id", OtherKey="id", IsForeignKey=true)]
		public TiposArea TiposArea
		{
			get
			{
				return this._TiposArea.Entity;
			}
			set
			{
				TiposArea previousValue = this._TiposArea.Entity;
				if (((previousValue != value) 
							|| (this._TiposArea.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TiposArea.Entity = null;
						previousValue.Preguntas.Remove(this);
					}
					this._TiposArea.Entity = value;
					if ((value != null))
					{
						value.Preguntas.Add(this);
						this._TipoArea_id = value.id;
					}
					else
					{
						this._TipoArea_id = default(int);
					}
					this.SendPropertyChanged("TiposArea");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RespuestasRevision(RespuestasRevision entity)
		{
			this.SendPropertyChanging();
			entity.Preguntas = this;
		}
		
		private void detach_RespuestasRevision(RespuestasRevision entity)
		{
			this.SendPropertyChanging();
			entity.Preguntas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RespuestasRevision")]
	public partial class RespuestasRevision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Revision_id;
		
		private int _Pregunta_id;
		
		private int _Respuesta_id;
		
		private string _Comentario;
		
		private string _FotoProblema;
		
		private string _FotoCierre;
		
		private System.Nullable<System.DateTime> _FechaCierre;
		
		private bool _HallazgoCerrado;
		
		private EntityRef<Preguntas> _Preguntas;
		
		private EntityRef<Revisiones> _Revisiones;
		
		private EntityRef<TiposRespuesta> _TiposRespuesta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnRevision_idChanging(int value);
    partial void OnRevision_idChanged();
    partial void OnPregunta_idChanging(int value);
    partial void OnPregunta_idChanged();
    partial void OnRespuesta_idChanging(int value);
    partial void OnRespuesta_idChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    partial void OnFotoProblemaChanging(string value);
    partial void OnFotoProblemaChanged();
    partial void OnFotoCierreChanging(string value);
    partial void OnFotoCierreChanged();
    partial void OnFechaCierreChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCierreChanged();
    partial void OnHallazgoCerradoChanging(bool value);
    partial void OnHallazgoCerradoChanged();
    #endregion
		
		public RespuestasRevision()
		{
			this._Preguntas = default(EntityRef<Preguntas>);
			this._Revisiones = default(EntityRef<Revisiones>);
			this._TiposRespuesta = default(EntityRef<TiposRespuesta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revision_id", DbType="Int NOT NULL")]
		public int Revision_id
		{
			get
			{
				return this._Revision_id;
			}
			set
			{
				if ((this._Revision_id != value))
				{
					if (this._Revisiones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRevision_idChanging(value);
					this.SendPropertyChanging();
					this._Revision_id = value;
					this.SendPropertyChanged("Revision_id");
					this.OnRevision_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pregunta_id", DbType="Int NOT NULL")]
		public int Pregunta_id
		{
			get
			{
				return this._Pregunta_id;
			}
			set
			{
				if ((this._Pregunta_id != value))
				{
					if (this._Preguntas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPregunta_idChanging(value);
					this.SendPropertyChanging();
					this._Pregunta_id = value;
					this.SendPropertyChanged("Pregunta_id");
					this.OnPregunta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Respuesta_id", DbType="Int NOT NULL")]
		public int Respuesta_id
		{
			get
			{
				return this._Respuesta_id;
			}
			set
			{
				if ((this._Respuesta_id != value))
				{
					if (this._TiposRespuesta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRespuesta_idChanging(value);
					this.SendPropertyChanging();
					this._Respuesta_id = value;
					this.SendPropertyChanged("Respuesta_id");
					this.OnRespuesta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(500)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoProblema", DbType="NVarChar(300)")]
		public string FotoProblema
		{
			get
			{
				return this._FotoProblema;
			}
			set
			{
				if ((this._FotoProblema != value))
				{
					this.OnFotoProblemaChanging(value);
					this.SendPropertyChanging();
					this._FotoProblema = value;
					this.SendPropertyChanged("FotoProblema");
					this.OnFotoProblemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoCierre", DbType="NVarChar(300)")]
		public string FotoCierre
		{
			get
			{
				return this._FotoCierre;
			}
			set
			{
				if ((this._FotoCierre != value))
				{
					this.OnFotoCierreChanging(value);
					this.SendPropertyChanging();
					this._FotoCierre = value;
					this.SendPropertyChanged("FotoCierre");
					this.OnFotoCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCierre
		{
			get
			{
				return this._FechaCierre;
			}
			set
			{
				if ((this._FechaCierre != value))
				{
					this.OnFechaCierreChanging(value);
					this.SendPropertyChanging();
					this._FechaCierre = value;
					this.SendPropertyChanged("FechaCierre");
					this.OnFechaCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoCerrado", DbType="Bit NOT NULL")]
		public bool HallazgoCerrado
		{
			get
			{
				return this._HallazgoCerrado;
			}
			set
			{
				if ((this._HallazgoCerrado != value))
				{
					this.OnHallazgoCerradoChanging(value);
					this.SendPropertyChanging();
					this._HallazgoCerrado = value;
					this.SendPropertyChanged("HallazgoCerrado");
					this.OnHallazgoCerradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Preguntas_RespuestasRevision", Storage="_Preguntas", ThisKey="Pregunta_id", OtherKey="id", IsForeignKey=true)]
		public Preguntas Preguntas
		{
			get
			{
				return this._Preguntas.Entity;
			}
			set
			{
				Preguntas previousValue = this._Preguntas.Entity;
				if (((previousValue != value) 
							|| (this._Preguntas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Preguntas.Entity = null;
						previousValue.RespuestasRevision.Remove(this);
					}
					this._Preguntas.Entity = value;
					if ((value != null))
					{
						value.RespuestasRevision.Add(this);
						this._Pregunta_id = value.id;
					}
					else
					{
						this._Pregunta_id = default(int);
					}
					this.SendPropertyChanged("Preguntas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Revisiones_RespuestasRevision", Storage="_Revisiones", ThisKey="Revision_id", OtherKey="id", IsForeignKey=true)]
		public Revisiones Revisiones
		{
			get
			{
				return this._Revisiones.Entity;
			}
			set
			{
				Revisiones previousValue = this._Revisiones.Entity;
				if (((previousValue != value) 
							|| (this._Revisiones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Revisiones.Entity = null;
						previousValue.RespuestasRevision.Remove(this);
					}
					this._Revisiones.Entity = value;
					if ((value != null))
					{
						value.RespuestasRevision.Add(this);
						this._Revision_id = value.id;
					}
					else
					{
						this._Revision_id = default(int);
					}
					this.SendPropertyChanged("Revisiones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposRespuesta_RespuestasRevision", Storage="_TiposRespuesta", ThisKey="Respuesta_id", OtherKey="id", IsForeignKey=true)]
		public TiposRespuesta TiposRespuesta
		{
			get
			{
				return this._TiposRespuesta.Entity;
			}
			set
			{
				TiposRespuesta previousValue = this._TiposRespuesta.Entity;
				if (((previousValue != value) 
							|| (this._TiposRespuesta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TiposRespuesta.Entity = null;
						previousValue.RespuestasRevision.Remove(this);
					}
					this._TiposRespuesta.Entity = value;
					if ((value != null))
					{
						value.RespuestasRevision.Add(this);
						this._Respuesta_id = value.id;
					}
					else
					{
						this._Respuesta_id = default(int);
					}
					this.SendPropertyChanged("TiposRespuesta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Revisiones")]
	public partial class Revisiones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Usuario_id;
		
		private int _ManagerSeccion_id;
		
		private System.DateTime _Fecha;
		
		private string _Check_id;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaFin;
		
		private System.Nullable<decimal> _Calificacion;
		
		private int _Estatus_id;
		
		private string _ComentarioRevisor;
		
		private bool _EntregadoTarde;
		
		private EntitySet<RespuestasRevision> _RespuestasRevision;
		
		private EntityRef<EstatusRevision> _EstatusRevision;
		
		private EntityRef<ManagerSecciones> _ManagerSecciones;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUsuario_idChanging(int value);
    partial void OnUsuario_idChanged();
    partial void OnManagerSeccion_idChanging(int value);
    partial void OnManagerSeccion_idChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnCheck_idChanging(string value);
    partial void OnCheck_idChanged();
    partial void OnFechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInicioChanged();
    partial void OnFechaFinChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaFinChanged();
    partial void OnCalificacionChanging(System.Nullable<decimal> value);
    partial void OnCalificacionChanged();
    partial void OnEstatus_idChanging(int value);
    partial void OnEstatus_idChanged();
    partial void OnComentarioRevisorChanging(string value);
    partial void OnComentarioRevisorChanged();
    partial void OnEntregadoTardeChanging(bool value);
    partial void OnEntregadoTardeChanged();
    #endregion
		
		public Revisiones()
		{
			this._RespuestasRevision = new EntitySet<RespuestasRevision>(new Action<RespuestasRevision>(this.attach_RespuestasRevision), new Action<RespuestasRevision>(this.detach_RespuestasRevision));
			this._EstatusRevision = default(EntityRef<EstatusRevision>);
			this._ManagerSecciones = default(EntityRef<ManagerSecciones>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_id", DbType="Int NOT NULL")]
		public int Usuario_id
		{
			get
			{
				return this._Usuario_id;
			}
			set
			{
				if ((this._Usuario_id != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuario_idChanging(value);
					this.SendPropertyChanging();
					this._Usuario_id = value;
					this.SendPropertyChanged("Usuario_id");
					this.OnUsuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerSeccion_id", DbType="Int NOT NULL")]
		public int ManagerSeccion_id
		{
			get
			{
				return this._ManagerSeccion_id;
			}
			set
			{
				if ((this._ManagerSeccion_id != value))
				{
					if (this._ManagerSecciones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManagerSeccion_idChanging(value);
					this.SendPropertyChanging();
					this._ManagerSeccion_id = value;
					this.SendPropertyChanged("ManagerSeccion_id");
					this.OnManagerSeccion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Check_id", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Check_id
		{
			get
			{
				return this._Check_id;
			}
			set
			{
				if ((this._Check_id != value))
				{
					this.OnCheck_idChanging(value);
					this.SendPropertyChanging();
					this._Check_id = value;
					this.SendPropertyChanged("Check_id");
					this.OnCheck_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFin
		{
			get
			{
				return this._FechaFin;
			}
			set
			{
				if ((this._FechaFin != value))
				{
					this.OnFechaFinChanging(value);
					this.SendPropertyChanging();
					this._FechaFin = value;
					this.SendPropertyChanged("FechaFin");
					this.OnFechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calificacion", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Calificacion
		{
			get
			{
				return this._Calificacion;
			}
			set
			{
				if ((this._Calificacion != value))
				{
					this.OnCalificacionChanging(value);
					this.SendPropertyChanging();
					this._Calificacion = value;
					this.SendPropertyChanged("Calificacion");
					this.OnCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus_id", DbType="Int NOT NULL")]
		public int Estatus_id
		{
			get
			{
				return this._Estatus_id;
			}
			set
			{
				if ((this._Estatus_id != value))
				{
					if (this._EstatusRevision.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstatus_idChanging(value);
					this.SendPropertyChanging();
					this._Estatus_id = value;
					this.SendPropertyChanged("Estatus_id");
					this.OnEstatus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioRevisor", DbType="VarChar(500)")]
		public string ComentarioRevisor
		{
			get
			{
				return this._ComentarioRevisor;
			}
			set
			{
				if ((this._ComentarioRevisor != value))
				{
					this.OnComentarioRevisorChanging(value);
					this.SendPropertyChanging();
					this._ComentarioRevisor = value;
					this.SendPropertyChanged("ComentarioRevisor");
					this.OnComentarioRevisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntregadoTarde", DbType="Bit NOT NULL")]
		public bool EntregadoTarde
		{
			get
			{
				return this._EntregadoTarde;
			}
			set
			{
				if ((this._EntregadoTarde != value))
				{
					this.OnEntregadoTardeChanging(value);
					this.SendPropertyChanging();
					this._EntregadoTarde = value;
					this.SendPropertyChanged("EntregadoTarde");
					this.OnEntregadoTardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Revisiones_RespuestasRevision", Storage="_RespuestasRevision", ThisKey="id", OtherKey="Revision_id")]
		public EntitySet<RespuestasRevision> RespuestasRevision
		{
			get
			{
				return this._RespuestasRevision;
			}
			set
			{
				this._RespuestasRevision.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstatusRevision_Revisiones", Storage="_EstatusRevision", ThisKey="Estatus_id", OtherKey="id", IsForeignKey=true)]
		public EstatusRevision EstatusRevision
		{
			get
			{
				return this._EstatusRevision.Entity;
			}
			set
			{
				EstatusRevision previousValue = this._EstatusRevision.Entity;
				if (((previousValue != value) 
							|| (this._EstatusRevision.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstatusRevision.Entity = null;
						previousValue.Revisiones.Remove(this);
					}
					this._EstatusRevision.Entity = value;
					if ((value != null))
					{
						value.Revisiones.Add(this);
						this._Estatus_id = value.id;
					}
					else
					{
						this._Estatus_id = default(int);
					}
					this.SendPropertyChanged("EstatusRevision");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManagerSecciones_Revisiones", Storage="_ManagerSecciones", ThisKey="ManagerSeccion_id", OtherKey="id", IsForeignKey=true)]
		public ManagerSecciones ManagerSecciones
		{
			get
			{
				return this._ManagerSecciones.Entity;
			}
			set
			{
				ManagerSecciones previousValue = this._ManagerSecciones.Entity;
				if (((previousValue != value) 
							|| (this._ManagerSecciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManagerSecciones.Entity = null;
						previousValue.Revisiones.Remove(this);
					}
					this._ManagerSecciones.Entity = value;
					if ((value != null))
					{
						value.Revisiones.Add(this);
						this._ManagerSeccion_id = value.id;
					}
					else
					{
						this._ManagerSeccion_id = default(int);
					}
					this.SendPropertyChanged("ManagerSecciones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Revisiones", Storage="_Usuarios", ThisKey="Usuario_id", OtherKey="id", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Revisiones.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Revisiones.Add(this);
						this._Usuario_id = value.id;
					}
					else
					{
						this._Usuario_id = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RespuestasRevision(RespuestasRevision entity)
		{
			this.SendPropertyChanging();
			entity.Revisiones = this;
		}
		
		private void detach_RespuestasRevision(RespuestasRevision entity)
		{
			this.SendPropertyChanging();
			entity.Revisiones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Rol;
		
		private EntitySet<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    #endregion
		
		public Roles()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Usuarios", Storage="_Usuarios", ThisKey="id", OtherKey="Rol_id")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiposArea")]
	public partial class TiposArea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Area;
		
		private EntitySet<ManagerSecciones> _ManagerSecciones;
		
		private EntitySet<Preguntas> _Preguntas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    #endregion
		
		public TiposArea()
		{
			this._ManagerSecciones = new EntitySet<ManagerSecciones>(new Action<ManagerSecciones>(this.attach_ManagerSecciones), new Action<ManagerSecciones>(this.detach_ManagerSecciones));
			this._Preguntas = new EntitySet<Preguntas>(new Action<Preguntas>(this.attach_Preguntas), new Action<Preguntas>(this.detach_Preguntas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposArea_ManagerSecciones", Storage="_ManagerSecciones", ThisKey="id", OtherKey="TipoArea_id")]
		public EntitySet<ManagerSecciones> ManagerSecciones
		{
			get
			{
				return this._ManagerSecciones;
			}
			set
			{
				this._ManagerSecciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposArea_Preguntas", Storage="_Preguntas", ThisKey="id", OtherKey="TipoArea_id")]
		public EntitySet<Preguntas> Preguntas
		{
			get
			{
				return this._Preguntas;
			}
			set
			{
				this._Preguntas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ManagerSecciones(ManagerSecciones entity)
		{
			this.SendPropertyChanging();
			entity.TiposArea = this;
		}
		
		private void detach_ManagerSecciones(ManagerSecciones entity)
		{
			this.SendPropertyChanging();
			entity.TiposArea = null;
		}
		
		private void attach_Preguntas(Preguntas entity)
		{
			this.SendPropertyChanging();
			entity.TiposArea = this;
		}
		
		private void detach_Preguntas(Preguntas entity)
		{
			this.SendPropertyChanging();
			entity.TiposArea = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiposCheck")]
	public partial class TiposCheck : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Tipo;
		
		private EntitySet<ManagerSecciones> _ManagerSecciones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public TiposCheck()
		{
			this._ManagerSecciones = new EntitySet<ManagerSecciones>(new Action<ManagerSecciones>(this.attach_ManagerSecciones), new Action<ManagerSecciones>(this.detach_ManagerSecciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposCheck_ManagerSecciones", Storage="_ManagerSecciones", ThisKey="id", OtherKey="TipoCheck_id")]
		public EntitySet<ManagerSecciones> ManagerSecciones
		{
			get
			{
				return this._ManagerSecciones;
			}
			set
			{
				this._ManagerSecciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ManagerSecciones(ManagerSecciones entity)
		{
			this.SendPropertyChanging();
			entity.TiposCheck = this;
		}
		
		private void detach_ManagerSecciones(ManagerSecciones entity)
		{
			this.SendPropertyChanging();
			entity.TiposCheck = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiposRespuesta")]
	public partial class TiposRespuesta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Respuesta;
		
		private EntitySet<RespuestasRevision> _RespuestasRevision;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnRespuestaChanging(string value);
    partial void OnRespuestaChanged();
    #endregion
		
		public TiposRespuesta()
		{
			this._RespuestasRevision = new EntitySet<RespuestasRevision>(new Action<RespuestasRevision>(this.attach_RespuestasRevision), new Action<RespuestasRevision>(this.detach_RespuestasRevision));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Respuesta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Respuesta
		{
			get
			{
				return this._Respuesta;
			}
			set
			{
				if ((this._Respuesta != value))
				{
					this.OnRespuestaChanging(value);
					this.SendPropertyChanging();
					this._Respuesta = value;
					this.SendPropertyChanged("Respuesta");
					this.OnRespuestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiposRespuesta_RespuestasRevision", Storage="_RespuestasRevision", ThisKey="id", OtherKey="Respuesta_id")]
		public EntitySet<RespuestasRevision> RespuestasRevision
		{
			get
			{
				return this._RespuestasRevision;
			}
			set
			{
				this._RespuestasRevision.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RespuestasRevision(RespuestasRevision entity)
		{
			this.SendPropertyChanging();
			entity.TiposRespuesta = this;
		}
		
		private void detach_RespuestasRevision(RespuestasRevision entity)
		{
			this.SendPropertyChanging();
			entity.TiposRespuesta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nombre;
		
		private string _Nomina;
		
		private string _Password;
		
		private int _Rol_id;
		
		private bool _Activo;
		
		private string _PreguntaRecuperacion;
		
		private string _RespuestaRecuperacion;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _UltimoRecordatorio;
		
		private EntitySet<ManagerSecciones> _ManagerSecciones;
		
		private EntitySet<Revisiones> _Revisiones;
		
		private EntityRef<Roles> _Roles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnNominaChanging(string value);
    partial void OnNominaChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRol_idChanging(int value);
    partial void OnRol_idChanged();
    partial void OnActivoChanging(bool value);
    partial void OnActivoChanged();
    partial void OnPreguntaRecuperacionChanging(string value);
    partial void OnPreguntaRecuperacionChanged();
    partial void OnRespuestaRecuperacionChanging(string value);
    partial void OnRespuestaRecuperacionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUltimoRecordatorioChanging(System.Nullable<System.DateTime> value);
    partial void OnUltimoRecordatorioChanged();
    #endregion
		
		public Usuarios()
		{
			this._ManagerSecciones = new EntitySet<ManagerSecciones>(new Action<ManagerSecciones>(this.attach_ManagerSecciones), new Action<ManagerSecciones>(this.detach_ManagerSecciones));
			this._Revisiones = new EntitySet<Revisiones>(new Action<Revisiones>(this.attach_Revisiones), new Action<Revisiones>(this.detach_Revisiones));
			this._Roles = default(EntityRef<Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomina", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nomina
		{
			get
			{
				return this._Nomina;
			}
			set
			{
				if ((this._Nomina != value))
				{
					this.OnNominaChanging(value);
					this.SendPropertyChanging();
					this._Nomina = value;
					this.SendPropertyChanged("Nomina");
					this.OnNominaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol_id", DbType="Int NOT NULL")]
		public int Rol_id
		{
			get
			{
				return this._Rol_id;
			}
			set
			{
				if ((this._Rol_id != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRol_idChanging(value);
					this.SendPropertyChanging();
					this._Rol_id = value;
					this.SendPropertyChanged("Rol_id");
					this.OnRol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreguntaRecuperacion", DbType="NVarChar(200)")]
		public string PreguntaRecuperacion
		{
			get
			{
				return this._PreguntaRecuperacion;
			}
			set
			{
				if ((this._PreguntaRecuperacion != value))
				{
					this.OnPreguntaRecuperacionChanging(value);
					this.SendPropertyChanging();
					this._PreguntaRecuperacion = value;
					this.SendPropertyChanged("PreguntaRecuperacion");
					this.OnPreguntaRecuperacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestaRecuperacion", DbType="NVarChar(200)")]
		public string RespuestaRecuperacion
		{
			get
			{
				return this._RespuestaRecuperacion;
			}
			set
			{
				if ((this._RespuestaRecuperacion != value))
				{
					this.OnRespuestaRecuperacionChanging(value);
					this.SendPropertyChanging();
					this._RespuestaRecuperacion = value;
					this.SendPropertyChanged("RespuestaRecuperacion");
					this.OnRespuestaRecuperacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoRecordatorio", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimoRecordatorio
		{
			get
			{
				return this._UltimoRecordatorio;
			}
			set
			{
				if ((this._UltimoRecordatorio != value))
				{
					this.OnUltimoRecordatorioChanging(value);
					this.SendPropertyChanging();
					this._UltimoRecordatorio = value;
					this.SendPropertyChanged("UltimoRecordatorio");
					this.OnUltimoRecordatorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_ManagerSecciones", Storage="_ManagerSecciones", ThisKey="id", OtherKey="Usuario_id")]
		public EntitySet<ManagerSecciones> ManagerSecciones
		{
			get
			{
				return this._ManagerSecciones;
			}
			set
			{
				this._ManagerSecciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Revisiones", Storage="_Revisiones", ThisKey="id", OtherKey="Usuario_id")]
		public EntitySet<Revisiones> Revisiones
		{
			get
			{
				return this._Revisiones;
			}
			set
			{
				this._Revisiones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Usuarios", Storage="_Roles", ThisKey="Rol_id", OtherKey="id", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._Rol_id = value.id;
					}
					else
					{
						this._Rol_id = default(int);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ManagerSecciones(ManagerSecciones entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_ManagerSecciones(ManagerSecciones entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_Revisiones(Revisiones entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Revisiones(Revisiones entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Secciones")]
	public partial class Secciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nombre;
		
		private bool _Activo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnActivoChanging(bool value);
    partial void OnActivoChanged();
    #endregion
		
		public Secciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notificaciones")]
	public partial class Notificaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Usuario_id;
		
		private string _Mensaje;
		
		private bool _Leida;
		
		private System.DateTime _FechaCreacion;
		
		private string _Url;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUsuario_idChanging(int value);
    partial void OnUsuario_idChanged();
    partial void OnMensajeChanging(string value);
    partial void OnMensajeChanged();
    partial void OnLeidaChanging(bool value);
    partial void OnLeidaChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    #endregion
		
		public Notificaciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_id", DbType="Int NOT NULL")]
		public int Usuario_id
		{
			get
			{
				return this._Usuario_id;
			}
			set
			{
				if ((this._Usuario_id != value))
				{
					this.OnUsuario_idChanging(value);
					this.SendPropertyChanging();
					this._Usuario_id = value;
					this.SendPropertyChanged("Usuario_id");
					this.OnUsuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this.OnMensajeChanging(value);
					this.SendPropertyChanging();
					this._Mensaje = value;
					this.SendPropertyChanged("Mensaje");
					this.OnMensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leida", DbType="Bit NOT NULL")]
		public bool Leida
		{
			get
			{
				return this._Leida;
			}
			set
			{
				if ((this._Leida != value))
				{
					this.OnLeidaChanging(value);
					this.SendPropertyChanging();
					this._Leida = value;
					this.SendPropertyChanged("Leida");
					this.OnLeidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(200)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
